export const MOCK_DATA = {
    // 资产分类
    assetCategories: [
        { id: 'stablecoins', name: 'Stablecoins', icon: 'coins', count: 10 },
        { id: 'us-treasuries', name: 'U.S. Treasuries', icon: 'landmark', count: 0 },
        { id: 'commodities', name: 'Commodities', icon: 'gem', count: 0 },
        { id: 'private-credit', name: 'Private Credit', icon: 'file-text', count: 0 },
        { id: 'stocks', name: 'Stocks', icon: 'trending-up', count: 0 },
        { id: 'institutional-funds', name: 'Institutional Funds', icon: 'building-columns', count: 0 },
        { id: 'non-us-govt-debt', name: 'Non-U.S. Govt. Debt', icon: 'globe', count: 0 },
        { id: 'corporate-bonds', name: 'Corporate Bonds', icon: 'building', count: 0 },
    ],

    // Stablecoins 分类详情数据
    stablecoinsData: {
        description: 'Explore the activity and risks behind crypto and asset-backed stablecoins. View encumbent and new issuer on-chain traction, regulatory information, and structural data.',
        metrics: [
            { label: 'Market Cap', value: '$297.68B', change: '-1.09%', trend: 'down' },
            { label: 'Monthly Transfer Volume', value: '$7.34T', change: '+34.98%', trend: 'up' },
            { label: 'Monthly Active Addresses', value: '45.07M', change: '+3.58%', trend: 'up' },
            { label: 'Holders', value: '220.12M', change: '+4.78%', trend: 'up' },
        ],
        // Stablecoin League Table - 按不同维度
        leagueTable: {
            platforms: [
                { rank: 1, name: 'Tether Holdings', logo: '🪙', rwaCount: 5, totalValue: '$177.5B', change30d: '+0.03%', trend: 'up', marketShare: '59.62%' },
                { rank: 2, name: 'Circle', logo: '⭕', rwaCount: 2, totalValue: '$72.4B', change30d: '-4.55%', trend: 'down', marketShare: '24.33%' },
                { rank: 3, name: 'MakerDAO', logo: '🔷', rwaCount: 1, totalValue: '$10.4B', change30d: '+0.27%', trend: 'up', marketShare: '3.50%' },
                { rank: 4, name: 'Binance', logo: '🔶', rwaCount: 2, totalValue: '$9.3B', change30d: '+0.15%', trend: 'up', marketShare: '3.12%' },
                { rank: 5, name: 'Ethena', logo: '⚫', rwaCount: 2, totalValue: '$7.3B', change30d: '-2.35%', trend: 'down', marketShare: '2.44%' },
                { rank: 6, name: 'Paxos', logo: '🟢', rwaCount: 5, totalValue: '$5.0B', change30d: '-3.72%', trend: 'down', marketShare: '1.68%' },
                { rank: 7, name: 'BitGo', logo: '🔵', rwaCount: 1, totalValue: '$3.4B', change30d: '+24.43%', trend: 'up', marketShare: '1.14%' },
                { rank: 8, name: 'Polygon Bridge', logo: '🟣', rwaCount: 3, totalValue: '$2.3B', change30d: '+6.32%', trend: 'up', marketShare: '0.77%' },
                { rank: 9, name: 'Falcon Finance', logo: '🦅', rwaCount: 1, totalValue: '$2.2B', change30d: '-2.51%', trend: 'down', marketShare: '0.73%' },
                { rank: 10, name: 'RLUSD', logo: '🌐', rwaCount: 1, totalValue: '$1.4B', change30d: '+5.20%', trend: 'up', marketShare: '0.47%' },
            ],
            managers: [
                { rank: 1, name: 'Usual', logo: '⚫', rwaCount: 1, totalValue: '$548.9M', change30d: '+0.10%', trend: 'up', marketShare: '43.39%' },
                { rank: 2, name: 'Resolv', logo: '🔷', rwaCount: 1, totalValue: '$329.0M', change30d: '+11.23%', trend: 'up', marketShare: '26.00%' },
                { rank: 3, name: 'StandX', logo: '🔵', rwaCount: 1, totalValue: '$142.4M', change30d: '+0.39%', trend: 'up', marketShare: '11.25%' },
                { rank: 4, name: 'VanEck Ass...', logo: '📊', rwaCount: 1, totalValue: '$115.7M', change30d: '-28.07%', trend: 'down', marketShare: '9.15%' },
                { rank: 5, name: 'Societe Ge...', logo: '🔷', rwaCount: 2, totalValue: '$99.6M', change30d: '+8.27%', trend: 'up', marketShare: '7.87%' },
                { rank: 6, name: 'Circle', logo: '⭕', rwaCount: 1, totalValue: '$11.8M', change30d: '-47.41%', trend: 'down', marketShare: '0.93%' },
                { rank: 7, name: 'Blackstone', logo: '⚫', rwaCount: 1, totalValue: '$8.7M', change30d: '+4.87%', trend: 'up', marketShare: '0.69%' },
                { rank: 8, name: 'Unitas Labs', logo: '🔵', rwaCount: 1, totalValue: '$5.7M', change30d: '+1.05%', trend: 'up', marketShare: '0.45%' },
                { rank: 9, name: 'Avenia', logo: '🟢', rwaCount: 1, totalValue: '$2.0M', change30d: '-5.41%', trend: 'down', marketShare: '0.16%' },
                { rank: 10, name: 'Tether Hold...', logo: '🪙', rwaCount: 1, totalValue: '$1.2M', change30d: '+1.32%', trend: 'up', marketShare: '0.10%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 74, totalValue: '$169.9B', change30d: '-1.17%', trend: 'down', marketShare: '57.08%' },
                { rank: 2, name: 'TRON', logo: '🔴', rwaCount: 5, totalValue: '$82.0B', change30d: '+2.03%', trend: 'up', marketShare: '27.55%' },
                { rank: 3, name: 'BNB Chain', logo: '🟡', rwaCount: 12, totalValue: '$12.8B', change30d: '+0.38%', trend: 'up', marketShare: '4.30%' },
                { rank: 4, name: 'Solana', logo: '🟣', rwaCount: 26, totalValue: '$12.7B', change30d: '-17.47%', trend: 'down', marketShare: '4.25%' },
                { rank: 5, name: 'Arbitrum', logo: '🔵', rwaCount: 13, totalValue: '$7.9B', change30d: '-2.15%', trend: 'down', marketShare: '2.65%' },
                { rank: 6, name: 'Base', logo: '🔵', rwaCount: 17, totalValue: '$4.5B', change30d: '-2.91%', trend: 'down', marketShare: '1.50%' },
                { rank: 7, name: 'Polygon', logo: '🟣', rwaCount: 21, totalValue: '$2.9B', change30d: '+6.17%', trend: 'up', marketShare: '0.99%' },
                { rank: 8, name: 'Avalanche...', logo: '🔴', rwaCount: 18, totalValue: '$2.1B', change30d: '+1.41%', trend: 'up', marketShare: '0.72%' },
                { rank: 9, name: 'Aptos', logo: '⬜', rwaCount: 3, totalValue: '$937.4M', change30d: '-16.52%', trend: 'down', marketShare: '0.31%' },
                { rank: 10, name: 'NEAR', logo: '🟢', rwaCount: 4, totalValue: '$558.9M', change30d: '+0.54%', trend: 'up', marketShare: '0.19%' },
            ],
            jurisdictions: [
                { rank: 1, name: 'United Stat...', logo: '🇺🇸', rwaCount: 21, totalValue: '$268.3B', change30d: '+0.99%', trend: 'up', marketShare: '90.99%' },
                { rank: 2, name: 'N/A', logo: '🌐', rwaCount: 23, totalValue: '$22.2B', change30d: '-1.70%', trend: 'down', marketShare: '7.52%' },
                { rank: 3, name: 'Germany', logo: '🇩🇪', rwaCount: 1, totalValue: '$3.7B', change30d: '-4.67%', trend: 'down', marketShare: '1.27%' },
                { rank: 4, name: 'British Virgi...', logo: '🇻🇬', rwaCount: 4, totalValue: '$464.7M', change30d: '+8.38%', trend: 'up', marketShare: '0.16%' },
                { rank: 5, name: 'Bermuda', logo: '🇧🇲', rwaCount: 2, totalValue: '$71.1M', change30d: '-13.82%', trend: 'down', marketShare: '0.02%' },
                { rank: 6, name: 'France', logo: '🇫🇷', rwaCount: 1, totalValue: '$69.6M', change30d: '+8.50%', trend: 'up', marketShare: '0.02%' },
                { rank: 7, name: 'The Baham...', logo: '🇧🇸', rwaCount: 1, totalValue: '$13.8M', change30d: '+1.24%', trend: 'up', marketShare: '0.00%' },
                { rank: 8, name: 'Singapore', logo: '🇸🇬', rwaCount: 3, totalValue: '$12.4M', change30d: '+0.49%', trend: 'up', marketShare: '0.00%' },
                { rank: 9, name: 'Republic of...', logo: '🏳️', rwaCount: 1, totalValue: '$11.8M', change30d: '-47.41%', trend: 'down', marketShare: '0.00%' },
                { rank: 10, name: 'Australia', logo: '🇦🇺', rwaCount: 2, totalValue: '$11.2M', change30d: '-9.17%', trend: 'down', marketShare: '0.00%' },
            ],
        },
        // Top 净流入/流出
        netFlows: [
            { symbol: 'USDT', provider: 'Tether Hol...', value: 2000000000, isPositive: true },
            { symbol: 'USD1', provider: 'BitGo', value: 668000000, isPositive: true },
            { symbol: 'PYUSD', provider: 'Paxos', value: -183000000, isPositive: false },
            { symbol: 'FDUSD', provider: 'First Digi...', value: -201000000, isPositive: false },
            { symbol: 'USDC', provider: 'Circle', value: -3400000000, isPositive: false },
        ],
        asOfDate: '01/13/2026',
    },

    // U.S. Treasuries 分类详情数据
    treasuriesData: {
        description: 'View tokenized US treasuries, bonds, and cash-equivalents and understand the nuances between them. Read our deep dive research report on tokenized treasuries on the RWA.xyz Research Blog.',
        metrics: [
            { label: 'Total Value', value: '$9.16B', change: '+1.50%', trend: 'up' },
            { label: '7D APY', value: '3.09%', change: '-1.37%', trend: 'down' },
            { label: 'Total Assets', value: '64', change: '', trend: 'stable' },
            { label: 'Holders', value: '58,999', change: '+0.03%', trend: 'up' },
        ],
        // 按网络分布的市值饼图数据
        marketCapsByNetwork: [
            { network: 'Ethereum', value: 4700000000, color: '#6B8AFF' },
            { network: 'BNB Chain', value: 1900000000, color: '#F0B90B' },
            { network: 'Stellar', value: 689500000, color: '#7C3AED' },
            { network: 'Solana', value: 543500000, color: '#9945FF' },
            { network: 'Aptos', value: 335800000, color: '#6B7280' },
            { network: 'Avalanche C-Chain', value: 221900000, color: '#E84142' },
            { network: 'Arbitrum', value: 188500000, color: '#28A0F0' },
        ],
        // Top Entities 排行榜 - 按不同维度
        topEntities: {
            platforms: [
                { rank: 1, name: 'Securitize', logo: '🔒', rwaCount: 3, totalValue: '$1.8B', change30d: '-5.41%', trend: 'down', marketShare: '19.79%' },
                { rank: 2, name: 'Circle', logo: '⭕', rwaCount: 1, totalValue: '$1.5B', change30d: '+12.76%', trend: 'up', marketShare: '16.62%' },
                { rank: 3, name: 'Ondo', logo: '🔷', rwaCount: 2, totalValue: '$1.5B', change30d: '-1.26%', trend: 'down', marketShare: '16.45%' },
                { rank: 4, name: 'Franklin Templeton Benji Inve...', logo: '🏛️', rwaCount: 1, totalValue: '$881.5M', change30d: '+7.65%', trend: 'up', marketShare: '9.63%' },
                { rank: 5, name: 'Libeara', logo: '📊', rwaCount: 1, totalValue: '$823.6M', change30d: '-2.13%', trend: 'down', marketShare: '9.00%' },
                { rank: 6, name: 'WisdomTree', logo: '🌳', rwaCount: 7, totalValue: '$743.0M', change30d: '+4.43%', trend: 'up', marketShare: '8.12%' },
                { rank: 7, name: 'Superstate', logo: '⚫', rwaCount: 1, totalValue: '$592.3M', change30d: '-2.30%', trend: 'down', marketShare: '6.47%' },
                { rank: 8, name: 'Centrifuge', logo: '🌀', rwaCount: 1, totalValue: '$323.8M', change30d: '+23.09%', trend: 'up', marketShare: '3.54%' },
                { rank: 9, name: 'Fidelity Investments', logo: '💎', rwaCount: 1, totalValue: '$237.8M', change30d: '-9.95%', trend: 'down', marketShare: '2.60%' },
                { rank: 10, name: 'Theo', logo: '🔵', rwaCount: 1, totalValue: '$155.6M', change30d: '-20.46%', trend: 'down', marketShare: '1.70%' },
            ],
            managers: [
                { rank: 1, name: 'BlackRock', logo: '⚫', rwaCount: 4, totalValue: '$1.8B', change30d: '-4.54%', trend: 'down', marketShare: '22.41%' },
                { rank: 2, name: 'Circle', logo: '⭕', rwaCount: 1, totalValue: '$1.5B', change30d: '+12.76%', trend: 'up', marketShare: '18.98%' },
                { rank: 3, name: 'Ondo', logo: '🔷', rwaCount: 2, totalValue: '$1.5B', change30d: '-1.26%', trend: 'down', marketShare: '18.79%' },
                { rank: 4, name: 'WisdomTree Digital Manage...', logo: '🌳', rwaCount: 7, totalValue: '$743.0M', change30d: '+4.43%', trend: 'up', marketShare: '9.27%' },
                { rank: 5, name: 'Federated Hermes', logo: '🔷', rwaCount: 1, totalValue: '$592.3M', change30d: '-2.30%', trend: 'down', marketShare: '7.39%' },
                { rank: 6, name: 'China Asset Management', logo: '🔴', rwaCount: 3, totalValue: '$546.8M', change30d: '+0.35%', trend: 'up', marketShare: '6.82%' },
                { rank: 7, name: 'Janus Henderson', logo: '🏛️', rwaCount: 1, totalValue: '$323.8M', change30d: '+23.09%', trend: 'up', marketShare: '4.04%' },
                { rank: 8, name: 'Fidelity Management & Rese...', logo: '💎', rwaCount: 1, totalValue: '$237.8M', change30d: '-9.95%', trend: 'down', marketShare: '2.97%' },
                { rank: 9, name: 'Wellington Management', logo: '⚫', rwaCount: 1, totalValue: '$176.0M', change30d: '-10.27%', trend: 'down', marketShare: '2.20%' },
                { rank: 10, name: 'Twenty First Capital', logo: '🔵', rwaCount: 1, totalValue: '$150.4M', change30d: '+20.07%', trend: 'up', marketShare: '1.88%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 42, totalValue: '$4.7B', change30d: '-3.05%', trend: 'down', marketShare: '51.86%' },
                { rank: 2, name: 'BNB Chain', logo: '🟡', rwaCount: 4, totalValue: '$1.9B', change30d: '+10.45%', trend: 'up', marketShare: '21.13%' },
                { rank: 3, name: 'Stellar', logo: '⚫', rwaCount: 11, totalValue: '$689.5M', change30d: '+14.50%', trend: 'up', marketShare: '7.53%' },
                { rank: 4, name: 'Solana', logo: '🟣', rwaCount: 11, totalValue: '$543.5M', change30d: '+2.66%', trend: 'up', marketShare: '5.94%' },
                { rank: 5, name: 'Aptos', logo: '⬜', rwaCount: 4, totalValue: '$335.8M', change30d: '-2.82%', trend: 'down', marketShare: '3.67%' },
                { rank: 6, name: 'Avalanche C-Chain', logo: '🔴', rwaCount: 20, totalValue: '$221.9M', change30d: '+8.80%', trend: 'up', marketShare: '2.42%' },
                { rank: 7, name: 'Arbitrum', logo: '🔵', rwaCount: 16, totalValue: '$188.5M', change30d: '+6.43%', trend: 'up', marketShare: '2.06%' },
                { rank: 8, name: 'XRP Ledger', logo: '⚫', rwaCount: 4, totalValue: '$158.0M', change30d: '+0.20%', trend: 'up', marketShare: '1.73%' },
                { rank: 9, name: 'Polygon', logo: '🟣', rwaCount: 9, totalValue: '$99.2M', change30d: '+19.54%', trend: 'up', marketShare: '1.08%' },
                { rank: 10, name: 'Base', logo: '🔵', rwaCount: 12, totalValue: '$60.6M', change30d: '+0.48%', trend: 'up', marketShare: '0.66%' },
            ],
            jurisdictions: [
                { rank: 1, name: 'United States of America', logo: '🇺🇸', rwaCount: 21, totalValue: '$6.5B', change30d: '+1.67%', trend: 'up', marketShare: '71.43%' },
                { rank: 2, name: 'British Virgin Islands', logo: '🇻🇬', rwaCount: 4, totalValue: '$1.3B', change30d: '+4.45%', trend: 'up', marketShare: '13.71%' },
                { rank: 3, name: 'Hong Kong', logo: '🇭🇰', rwaCount: 6, totalValue: '$668.6M', change30d: '+2.39%', trend: 'up', marketShare: '7.30%' },
                { rank: 4, name: 'N/A', logo: '🌐', rwaCount: 9, totalValue: '$218.8M', change30d: '-12.20%', trend: 'down', marketShare: '2.39%' },
                { rank: 5, name: 'Singapore', logo: '🇸🇬', rwaCount: 5, totalValue: '$208.2M', change30d: '-8.23%', trend: 'down', marketShare: '2.27%' },
                { rank: 6, name: 'European Union', logo: '🇪🇺', rwaCount: 1, totalValue: '$150.4M', change30d: '+20.07%', trend: 'up', marketShare: '1.64%' },
                { rank: 7, name: 'Switzerland', logo: '🇨🇭', rwaCount: 3, totalValue: '$59.6M', change30d: '+20.80%', trend: 'up', marketShare: '0.65%' },
                { rank: 8, name: 'Germany', logo: '🇩🇪', rwaCount: 1, totalValue: '$37.1M', change30d: '+29.13%', trend: 'up', marketShare: '0.41%' },
                { rank: 9, name: 'Luxembourg', logo: '🇱🇺', rwaCount: 1, totalValue: '$15.7M', change30d: '+0.32%', trend: 'up', marketShare: '0.17%' },
                { rank: 10, name: 'Cayman Islands', logo: '🇰🇾', rwaCount: 1, totalValue: '$2.0M', change30d: '+0.25%', trend: 'up', marketShare: '0.02%' },
            ],
        },
        // Top 净流入/流出
        netFlows: [
            { symbol: 'USYC', provider: 'Circle', value: 169000000, isPositive: true },
            { symbol: 'JTRSY', provider: 'Centrifuge', value: 60000000, isPositive: true },
            { symbol: 'WTGXX', provider: 'WisdomTree', value: 32000000, isPositive: true },
            { symbol: 'ULTRA', provider: 'Libeara', value: -21000000, isPositive: false },
            { symbol: 'USDY', provider: 'Ondo', value: -23000000, isPositive: false },
            { symbol: 'FDIT', provider: 'Fidelity I...', value: -26000000, isPositive: false },
            { symbol: 'thBILL', provider: 'Theo', value: -40000000, isPositive: false },
            { symbol: 'BUIDL', provider: 'Securitize', value: -95000000, isPositive: false },
        ],
        // 产品列表
        products: [
            { name: 'BlackRock USD Institutional Digital Liquidity Fund', issuer: 'BlackRock USD Institutional Digital Liquidity Fund', ticker: 'BUIDL', platform: 'Securitize', networks: ['ETH', 'APT', 'ARB', 'AVAX', 'OP'], marketCap: 1731829255, apy: 3.49 },
            { name: 'Circle USYC', issuer: 'Circle International', ticker: 'USYC', platform: 'Circle', networks: ['ETH', 'ARB', 'SOL'], marketCap: 1521315215, apy: 3.22 },
            { name: 'Franklin OnChain U.S. Government Money Fund', issuer: 'Franklin Templeton', ticker: 'BENJI', platform: 'Franklin Templet...', networks: ['ETH', 'APT', 'AVAX', 'ARB', 'BASE', 'SOL', 'STELLAR'], marketCap: 881538057, apy: 3.55 },
            { name: 'Ondo Short-Term US Government Bond Fund', issuer: 'Ondo I', ticker: 'OUSG', platform: 'Ondo', networks: ['ETH', 'SOL'], marketCap: 825914235, apy: 3.43 },
            { name: 'WisdomTree Government Money Market Digital ...', issuer: 'WisdomTree Government Money Market Digital Fund', ticker: 'WTGXX', platform: 'WisdomTree', networks: ['ETH', 'STELLAR', 'ALGO'], marketCap: 736582438, apy: 3.48 },
            { name: 'Ondo U.S. Dollar Yield', issuer: 'Ondo USDY', ticker: 'USDY', platform: 'Ondo', networks: ['ETH', 'SOL', 'NOBLE', 'MANTLE', 'SUI'], marketCap: 680193368, apy: 3.63 },
            { name: 'Superstate Short Duration US Government Secu...', issuer: 'Superstate Asset Trust', ticker: 'USTB', platform: 'Superstate', networks: ['ETH', 'SOL'], marketCap: 592297596, apy: 3.09 },
            { name: 'ChinaAMC USD Digital Money Market Fund Cla...', issuer: 'ChinaAMC', ticker: 'CUMIU', platform: 'Libeara', networks: ['ETH'], marketCap: 511395859, apy: 0.00 },
            { name: 'Janus Henderson Anemoy Treasury Fund', issuer: 'Anemoy', ticker: 'JTRSY', platform: 'Centrifuge', networks: ['ETH', 'ARB', 'CELO'], marketCap: 323754779, apy: 3.15 },
        ],
        asOfDate: '01/13/2026',
    },

    // Commodities 数据
    commoditiesData: {
        description: 'Explore the world of tokenized commodities, digital assets pegged to commodity assets like gold, silver, and oil. Understand their mechanisms, benefits, and risks.',
        metrics: [
            { label: 'Market Cap', value: '$4.18B', change: '+12.64%', trend: 'up' },
            { label: 'Monthly Transfer Volume', value: '$5.41B', change: '+50.35%', trend: 'up' },
            { label: 'Monthly Active Addresses', value: '27,910', change: '+44.64%', trend: 'up' },
            { label: 'Holders', value: '185.73K', change: '+9.20%', trend: 'up' },
        ],
        // Market Caps 按网络分布
        marketCapsByNetwork: [
            { network: 'Ethereum', value: 3700000000, color: '#6B8AFF' },
            { network: 'Polygon', value: 345600000, color: '#8247E5' },
            { network: 'XRP Ledger', value: 111900000, color: '#23292F' },
            { network: 'BNB Chain', value: 24400000, color: '#F0B90B' },
        ],
        // Top Entities - 只有 Managers 和 Networks
        topEntities: {
            managers: [
                { rank: 1, name: 'Tether', logo: '🪙', rwaCount: 1, totalValue: '$1.9B', change30d: '+14.16%', trend: 'up', marketShare: '47.06%' },
                { rank: 2, name: 'Paxos', logo: '🟢', rwaCount: 1, totalValue: '$1.7B', change30d: '+18.46%', trend: 'up', marketShare: '42.86%' },
                { rank: 3, name: 'Justoken', logo: '⚫', rwaCount: 4, totalValue: '$345.6M', change30d: '-29.12%', trend: 'down', marketShare: '8.53%' },
                { rank: 4, name: 'Matrixdock', logo: '🔵', rwaCount: 1, totalValue: '$59.1M', change30d: '-5.60%', trend: 'down', marketShare: '1.46%' },
                { rank: 5, name: 'WisdomTre...', logo: '🌳', rwaCount: 1, totalValue: '$2.1M', change30d: '+34.05%', trend: 'up', marketShare: '0.05%' },
                { rank: 6, name: 'Mineral Vau...', logo: '💎', rwaCount: 1, totalValue: '$1.7M', change30d: '-2.11%', trend: 'down', marketShare: '0.04%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 8, totalValue: '$3.7B', change30d: '+16.08%', trend: 'up', marketShare: '87.85%' },
                { rank: 2, name: 'Polygon', logo: '🟣', rwaCount: 4, totalValue: '$345.6M', change30d: '-29.12%', trend: 'down', marketShare: '8.26%' },
                { rank: 3, name: 'XRP Ledger', logo: '⚫', rwaCount: 5, totalValue: '$111.9M', change30d: '', trend: 'neutral', marketShare: '2.68%' },
                { rank: 4, name: 'BNB Chain', logo: '🟡', rwaCount: 1, totalValue: '$24.4M', change30d: '-5.57%', trend: 'down', marketShare: '0.58%' },
                { rank: 5, name: 'XDC', logo: '🔵', rwaCount: 1, totalValue: '$15.9M', change30d: '', trend: 'neutral', marketShare: '0.38%' },
                { rank: 6, name: 'Plume', logo: '🔴', rwaCount: 2, totalValue: '$6.2M', change30d: '-4.65%', trend: 'down', marketShare: '0.15%' },
                { rank: 7, name: 'Stellar', logo: '⚫', rwaCount: 1, totalValue: '$2.1M', change30d: '+34.05%', trend: 'up', marketShare: '0.05%' },
                { rank: 8, name: 'Solana', logo: '🟣', rwaCount: 1, totalValue: '$1.9M', change30d: '+14.40%', trend: 'up', marketShare: '0.05%' },
                { rank: 9, name: 'Avalanche...', logo: '🔴', rwaCount: 1, totalValue: '$1.4K', change30d: '-1.88%', trend: 'down', marketShare: '0.00%' },
            ],
        },
        // 产品列表
        products: [
            { name: 'Tether Gold', issuer: 'Tether Holdings', ticker: 'XAUT', platform: 'Tether Holdings', networks: ['ETH', 'TRX'], peggedCommodity: 'Gold (ounces)', sector: 'Precious Metals', marketCap: 1903049323 },
            { name: 'Paxos Gold', issuer: 'Paxos', ticker: 'PAXG', platform: 'Paxos', networks: ['ETH'], peggedCommodity: 'Gold (ounces)', sector: 'Precious Metals', marketCap: 1735569518 },
            { name: 'JSOY_OIL', issuer: 'Justoken', ticker: 'JSOY_OIL', platform: 'Justoken', networks: ['POL'], peggedCommodity: 'Soybean Oil (pounds)', sector: 'Agriculture', marketCap: 301055494 },
            { name: 'Matrixdock Gold', issuer: 'Matrixdock', ticker: 'XAUm', platform: 'Matrixdock', networks: ['ETH', 'BNB'], peggedCommodity: 'Gold (ounces)', sector: 'Precious Metals', marketCap: 59325279 },
            { name: 'Diamonds: SD Collectio...', issuer: 'Ctrl Alt', ticker: 'DIA-SD...', platform: 'Ctrl Alt', networks: ['XRP'], peggedCommodity: '—', sector: '—', marketCap: 47260312 },
            { name: 'Diamonds: FS Collectio...', issuer: 'Ctrl Alt', ticker: 'DIA-FS...', platform: 'Ctrl Alt', networks: ['XRP'], peggedCommodity: '—', sector: '—', marketCap: 35320474 },
            { name: 'JSOY', issuer: 'Justoken', ticker: 'JSOY', platform: 'Justoken', networks: ['POL'], peggedCommodity: 'Soybeans (bushels)', sector: 'Agriculture', marketCap: 20361440 },
            { name: 'JCOT', issuer: 'Justoken', ticker: 'JCOT', platform: 'Justoken', networks: ['POL'], peggedCommodity: 'Cotton (pounds)', sector: 'Agriculture', marketCap: 19159617 },
            { name: 'Comtech Gold', issuer: 'Comtech Gold', ticker: 'CGO', platform: 'Comtech Gold', networks: ['XDC'], peggedCommodity: 'Gold (grams)', sector: 'Precious Metals', marketCap: 15880159 },
            { name: 'Diamonds: S Collection 1', issuer: 'Ctrl Alt', ticker: 'DIA-S...', platform: 'Ctrl Alt', networks: ['XRP'], peggedCommodity: '—', sector: '—', marketCap: 15233173 },
        ],
        asOfDate: '01/14/2026',
    },

    // Stocks 数据
    stocksData: {
        description: 'Explore tokenized public stocks, including tokenized versions of listed equities and natively issued onchain stocks. Dive into our comprehensive analysis on tokenized stocks.',
        metrics: [
            { label: 'Total Value', value: '$807.68M', change: '+11.43%', trend: 'up' },
            { label: 'Monthly Transfer Volume', value: '$2.25B', change: '+37.14%', trend: 'up' },
            { label: 'Monthly Active Addresses', value: '37,854', change: '-27.47%', trend: 'down' },
            { label: 'Holders', value: '154.22K', change: '+20.81%', trend: 'up' },
        ],
        // Total Value 按网络分布
        totalValueByNetwork: [
            { network: 'Ethereum', value: 367900000, color: '#6B8AFF' },
            { network: 'Solana', value: 198800000, color: '#9945FF' },
            { network: 'Algorand', value: 146800000, color: '#000000' },
            { network: 'BNB Chain', value: 62700000, color: '#F0B90B' },
            { network: 'Stellar', value: 23100000, color: '#000000' },
            { network: 'Gnosis', value: 4600000, color: '#04795B' },
            { network: 'Plume', value: 0, color: '#E84142' },
        ],
        // League Table - Platforms, Underlying Stock, Networks
        leagueTable: {
            platforms: [
                { rank: 1, name: 'Ondo', logo: '🔷', rwaCount: 201, totalValue: '$415.9M', change30d: '+13.84%', trend: 'up', marketShare: '51.50%' },
                { rank: 2, name: 'xStocks', logo: '❌', rwaCount: 74, totalValue: '$191.5M', change30d: '+3.11%', trend: 'up', marketShare: '23.71%' },
                { rank: 3, name: 'Securitize', logo: '🔒', rwaCount: 1, totalValue: '$146.8M', change30d: '+7.29%', trend: 'up', marketShare: '18.18%' },
                { rank: 4, name: 'WisdomTree', logo: '🌳', rwaCount: 5, totalValue: '$23.1M', change30d: '+1.85%', trend: 'up', marketShare: '2.86%' },
                { rank: 5, name: 'Superstate O...', logo: '⚫', rwaCount: 3, totalValue: '$16.2M', change30d: '+1282%', trend: 'up', marketShare: '2.01%' },
                { rank: 6, name: 'Backed Finan...', logo: '🔵', rwaCount: 3, totalValue: '$5.7M', change30d: '-3.50%', trend: 'down', marketShare: '0.71%' },
                { rank: 7, name: 'Remora Mark...', logo: '🔴', rwaCount: 5, totalValue: '$4.6M', change30d: '+36.17%', trend: 'up', marketShare: '0.57%' },
                { rank: 8, name: 'Dinari', logo: '🟠', rwaCount: 88, totalValue: '$3.0M', change30d: '+1.59%', trend: 'up', marketShare: '0.37%' },
                { rank: 9, name: 'Swarm', logo: '🔵', rwaCount: 8, totalValue: '$638.20K', change30d: '-5.61%', trend: 'down', marketShare: '0.08%' },
                { rank: 10, name: 'Centrifuge', logo: '🌀', rwaCount: 1, totalValue: '$111.20K', change30d: '+0.93%', trend: 'up', marketShare: '0.01%' },
            ],
            underlyingStock: [
                { rank: 1, name: 'Exodus Move...', logo: '💎', rwaCount: 1, totalValue: '$146.8M', change30d: '+7.29%', trend: 'up', marketShare: '18.83%' },
                { rank: 2, name: 'Tesla Inc. DL ...', logo: '🔴', rwaCount: 4, totalValue: '$66.7M', change30d: '+21.43%', trend: 'up', marketShare: '8.55%' },
                { rank: 3, name: 'Circle Interne...', logo: '🌐', rwaCount: 2, totalValue: '$42.2M', change30d: '+21.09%', trend: 'up', marketShare: '5.41%' },
                { rank: 4, name: 'SPDR S&P 50...', logo: '📊', rwaCount: 3, totalValue: '$40.5M', change30d: '-7.54%', trend: 'down', marketShare: '5.19%' },
                { rank: 5, name: 'The Invesco ...', logo: '🌐', rwaCount: 3, totalValue: '$34.2M', change30d: '-7.36%', trend: 'down', marketShare: '4.39%' },
                { rank: 6, name: 'Alphabet Inc. ...', logo: '🌐', rwaCount: 3, totalValue: '$31.5M', change30d: '+26.02%', trend: 'up', marketShare: '4.03%' },
                { rank: 7, name: 'NVIDIA Corp', logo: '🟢', rwaCount: 5, totalValue: '$25.9M', change30d: '-23.81%', trend: 'down', marketShare: '3.32%' },
                { rank: 8, name: 'iShares Silver ...', logo: '🌐', rwaCount: 1, totalValue: '$22.0M', change30d: '+80.98%', trend: 'up', marketShare: '2.82%' },
                { rank: 9, name: 'iShares Core ...', logo: '🌐', rwaCount: 1, totalValue: '$21.8M', change30d: '+2.15%', trend: 'up', marketShare: '2.80%' },
                { rank: 10, name: 'iShares 20+ Y...', logo: '🌐', rwaCount: 1, totalValue: '$17.8M', change30d: '+2.50%', trend: 'up', marketShare: '2.29%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 371, totalValue: '$367.9M', change30d: '+6.44%', trend: 'up', marketShare: '45.55%' },
                { rank: 2, name: 'Solana', logo: '🟣', rwaCount: 282, totalValue: '$198.8M', change30d: '+12.00%', trend: 'up', marketShare: '24.61%' },
                { rank: 3, name: 'Algorand', logo: '⚫', rwaCount: 1, totalValue: '$146.8M', change30d: '+7.29%', trend: 'up', marketShare: '18.18%' },
                { rank: 4, name: 'BNB Chain', logo: '🟡', rwaCount: 275, totalValue: '$62.7M', change30d: '+85.67%', trend: 'up', marketShare: '7.77%' },
                { rank: 5, name: 'Stellar', logo: '⚫', rwaCount: 5, totalValue: '$23.1M', change30d: '+1.85%', trend: 'up', marketShare: '2.86%' },
                { rank: 6, name: 'Gnosis', logo: '🟢', rwaCount: 2, totalValue: '$4.6M', change30d: '-1.50%', trend: 'down', marketShare: '0.57%' },
                { rank: 7, name: 'Arbitrum', logo: '🔵', rwaCount: 165, totalValue: '$2.8M', change30d: '+2.26%', trend: 'up', marketShare: '0.34%' },
                { rank: 8, name: 'Polygon', logo: '🟣', rwaCount: 8, totalValue: '$638.20K', change30d: '-5.61%', trend: 'down', marketShare: '0.08%' },
                { rank: 9, name: 'Base', logo: '🔵', rwaCount: 93, totalValue: '$320.10K', change30d: '-4.02%', trend: 'down', marketShare: '0.04%' },
                { rank: 10, name: 'Plume', logo: '🔴', rwaCount: 5, totalValue: '$0', change30d: '-100.0%', trend: 'down', marketShare: '0.00%' },
            ],
        },
        // 产品列表
        products: [
            { name: 'Exodus Movement Inc.', issuer: 'Exodus', ticker: 'EXOD', platform: 'Securitize', networks: ['ALGO'], totalValue: 163976250, underlyingAsset: 'Exodus Movement Inc.', nav: 18.25 },
            { name: 'Tesla xStock', issuer: 'Backed Assets', ticker: 'TSLAx', platform: 'xStocks', networks: ['ETH', 'SOL', 'BNB'], totalValue: 49980744, underlyingAsset: 'Tesla Inc. DL - 001', nav: 449 },
            { name: 'SPDR S&P 500 ETF (On...', issuer: 'Ondo Global Markets', ticker: 'SPYon', platform: 'Ondo', networks: ['ETH', 'SOL'], totalValue: 27292794, underlyingAsset: 'SPDR S&P 500 ETF Tr...', nav: 695 },
            { name: 'Alphabet Class A (Ondo...', issuer: 'Ondo Global Markets', ticker: 'GOOGLon', platform: 'Ondo', networks: ['ETH', 'SOL'], totalValue: 24431266, underlyingAsset: 'Alphabet Inc. Class A', nav: 332 },
            { name: 'iShares Silver Trust (Ond...', issuer: 'Ondo Global Markets', ticker: 'SLVon', platform: 'Ondo', networks: ['ETH', 'SOL'], totalValue: 24169043, underlyingAsset: 'iShares Silver Trust', nav: 77.23 },
            { name: 'CRCLx xStock', issuer: 'Backed Assets', ticker: 'CRCLx', platform: 'xStocks', networks: ['ETH', 'SOL'], totalValue: 23912693, underlyingAsset: 'Circle Internet Group', nav: 82.90 },
            { name: 'Invesco QQQ (Ondo To...', issuer: 'Ondo Global Markets', ticker: 'QQQon', platform: 'Ondo', networks: ['ETH', 'SOL'], totalValue: 23118975, underlyingAsset: 'The Invesco QQQ Tr...', nav: 627 },
            { name: 'iShares Core S&P 500 E...', issuer: 'Ondo Global Markets', ticker: 'IVVon', platform: 'Ondo', networks: ['ETH', 'SOL'], totalValue: 21913258, underlyingAsset: 'iShares Core S&P 5...', nav: 698 },
        ],
        asOfDate: '01/14/2026',
    },

    // Non-US Government Debt 数据
    nonUsGovtDebtData: {
        description: 'View data on tokenized non-U.S. government debt, digital assets that are backed by public debt issued by governments and municipalities.',
        metrics: [
            { label: 'Total Value', value: '$813.49M', change: '+4.42%', trend: 'up' },
            { label: 'Total Assets', value: '19', change: '', trend: 'neutral' },
            { label: 'Holders', value: '2,227', change: '+0.50%', trend: 'up' },
        ],
        // Total Value 按资产分布
        totalValueByAsset: [
            { asset: 'Spiko EU T-Bills Money Market Fund', value: 560800000, color: '#8B8AFF' },
            { asset: 'ChinaAMC HKD Digital Money Market Fund Class A HKD', value: 89900000, color: '#FFB366' },
            { asset: 'A&I CAMC RMB TMMF', value: 71800000, color: '#FFEAB5' },
            { asset: 'ChinaAMC RMB Digital Money Market Fund Class B RMB', value: 30900000, color: '#FFE5CC' },
            { asset: 'A&I CAMC HKD TMMF', value: 25800000, color: '#D4E5FF' },
        ],
        // Top Entities - Platforms, Managers, Networks, Jurisdiction Country
        topEntities: {
            platforms: [
                { rank: 1, name: 'Spiko', logo: '🔷', rwaCount: 2, totalValue: '$561.7M', change30d: '+38.57%', trend: 'up', marketShare: '69.05%' },
                { rank: 2, name: 'Libeara', logo: '📊', rwaCount: 8, totalValue: '$224.7M', change30d: '+0.42%', trend: 'up', marketShare: '27.62%' },
                { rank: 3, name: 'Backed Finan...', logo: '🔵', rwaCount: 1, totalValue: '$10.0M', change30d: '-0.78%', trend: 'down', marketShare: '1.23%' },
                { rank: 4, name: 'OpenTrade (P...', logo: '🌐', rwaCount: 3, totalValue: '$9.3M', change30d: '+14.17%', trend: 'up', marketShare: '1.14%' },
                { rank: 5, name: 'Etherfuse', logo: '🟢', rwaCount: 4, totalValue: '$7.8M', change30d: '+15.68%', trend: 'up', marketShare: '0.96%' },
                { rank: 6, name: 'Archax', logo: '🔴', rwaCount: 1, totalValue: '$0.4', change30d: '-0.97%', trend: 'down', marketShare: '0.00%' },
            ],
            managers: [
                { rank: 1, name: 'Twenty First ...', logo: '📈', rwaCount: 2, totalValue: '$561.7M', change30d: '+38.57%', trend: 'up', marketShare: '71.32%' },
                { rank: 2, name: 'China Asset ...', logo: '🇨🇳', rwaCount: 8, totalValue: '$224.7M', change30d: '+0.42%', trend: 'up', marketShare: '28.53%' },
                { rank: 3, name: 'Five Sigma', logo: '5️⃣', rwaCount: 1, totalValue: '$1.2M', change30d: '+8.69%', trend: 'up', marketShare: '0.15%' },
                { rank: 4, name: 'abrdn Invest...', logo: '📊', rwaCount: 1, totalValue: '$0.4', change30d: '-0.97%', trend: 'down', marketShare: '0.00%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 12, totalValue: '$238.5M', change30d: '+0.19%', trend: 'up', marketShare: '29.32%' },
                { rank: 2, name: 'Arbitrum', logo: '🔵', rwaCount: 2, totalValue: '$235.6M', change30d: '+5.14%', trend: 'up', marketShare: '28.96%' },
                { rank: 3, name: 'Stellar', logo: '⚫', rwaCount: 3, totalValue: '$166.7M', change30d: '+897.7%', trend: 'up', marketShare: '20.49%' },
                { rank: 4, name: 'Polygon', logo: '🟣', rwaCount: 3, totalValue: '$131.2M', change30d: '-4.12%', trend: 'down', marketShare: '16.13%' },
                { rank: 5, name: 'Base', logo: '🔵', rwaCount: 3, totalValue: '$30.3M', change30d: '+11.25%', trend: 'up', marketShare: '3.72%' },
                { rank: 6, name: 'Avalanche C-...', logo: '🔴', rwaCount: 2, totalValue: '$8.1M', change30d: '-0.64%', trend: 'down', marketShare: '1.00%' },
                { rank: 7, name: 'Solana', logo: '🟣', rwaCount: 4, totalValue: '$3.0M', change30d: '+3.37%', trend: 'up', marketShare: '0.37%' },
                { rank: 8, name: 'XRP Ledger', logo: '⚫', rwaCount: 1, totalValue: '$0.4', change30d: '-0.97%', trend: 'down', marketShare: '0.00%' },
            ],
            jurisdictions: [
                { rank: 1, name: 'European Uni...', logo: '🇪🇺', rwaCount: 2, totalValue: '$561.7M', change30d: '+38.57%', trend: 'up', marketShare: '69.05%' },
                { rank: 2, name: 'Hong Kong', logo: '🇭🇰', rwaCount: 8, totalValue: '$224.7M', change30d: '+0.42%', trend: 'up', marketShare: '27.62%' },
                { rank: 3, name: 'Switzerland', logo: '🇨🇭', rwaCount: 5, totalValue: '$17.8M', change30d: '+5.82%', trend: 'up', marketShare: '2.19%' },
                { rank: 4, name: 'N/A', logo: '🌐', rwaCount: 3, totalValue: '$9.3M', change30d: '+14.17%', trend: 'up', marketShare: '1.14%' },
                { rank: 5, name: 'Ireland', logo: '🇮🇪', rwaCount: 1, totalValue: '$0.4', change30d: '-0.97%', trend: 'down', marketShare: '0.00%' },
            ],
        },
        // 产品列表
        products: [
            { name: 'Spiko EU T-Bills Money Market Fund', issuer: 'Spiko', ticker: 'EUTBL', platform: 'Spiko', networks: ['ETH', 'POL', 'BASE'], marketCap: 560808149, eligibleInvestors: 'Non-U.S. Investor', holders: 1720 },
            { name: 'ChinaAMC HKD Digital Money Market Fund Cla...', issuer: 'ChinaAMC', ticker: 'CAMMF', platform: 'Libeara', networks: ['ETH'], marketCap: 89869360, eligibleInvestors: 'Non-U.S. Investor', holders: 3 },
            { name: 'A&I CAMC RMB TMMF', issuer: 'ChinaAMC', ticker: 'AICRT', platform: 'Libeara', networks: ['ETH'], marketCap: 71760356, eligibleInvestors: 'Non-U.S. Accredited ...', holders: 2 },
            { name: 'ChinaAMC RMB Digital Money Market Fund Cla...', issuer: 'ChinaAMC', ticker: 'CRMBR', platform: 'Libeara', networks: ['ETH'], marketCap: 30934958, eligibleInvestors: 'Non-U.S. Investor', holders: 2 },
            { name: 'A&I CAMC HKD TMMF', issuer: 'ChinaAMC', ticker: 'AICHT', platform: 'Libeara', networks: ['ETH'], marketCap: 25825157, eligibleInvestors: 'Non-U.S. Accredited ...', holders: 1 },
            { name: 'Backed GOVIES 0-6 Months Euro Investment Gr...', issuer: 'Backed Assets', ticker: 'bC3M', platform: 'Backed Finance', networks: ['ETH'], marketCap: 9987424, eligibleInvestors: '—', holders: 5 },
            { name: 'OpenTrade Fixed Term E.U. Bonds Vault', issuer: 'OpenTrade', ticker: 'XEVT', platform: 'OpenTrade (Peri...', networks: ['AVAX'], marketCap: 6948099, eligibleInvestors: '—', holders: 5 },
            { name: 'Etherfuse CETES', issuer: 'Etherfuse', ticker: 'CETES', platform: 'Etherfuse', networks: ['ETH', 'SOL'], marketCap: 6592279, eligibleInvestors: 'Non-U.S. Investor', holders: 284 },
            { name: 'ChinaAMC RMB Digital Money Market Fund Cla...', issuer: 'ChinaAMC', ticker: 'CRMFR', platform: 'Libeara', networks: ['ETH'], marketCap: 4283783, eligibleInvestors: 'Non-U.S. Investor', holders: 2 },
            { name: 'ChinaAMC HKD Digital Money Market Fund Cla...', issuer: 'ChinaAMC', ticker: 'CAMFF', platform: 'Libeara', networks: ['ETH'], marketCap: 2031837, eligibleInvestors: 'Non-U.S. Investor', holders: 4 },
        ],
        asOfDate: '01/14/2026',
    },

    // Private Credit 数据
    privateCreditData: {
        description: 'Earn real yields by investing in private credit loans to businesses, a $1.6T market in traditional finance. Credit platforms facilitate originations, deal funding, and borrower repayments.',
        metrics: [
            { label: 'Active Loans Value', value: '$19.86B', change: '', trend: 'neutral' },
            { label: 'Total Loans Value', value: '$36.45B', change: '', trend: 'neutral' },
            { label: 'Current Avg. APR', value: '10.14%', change: '', trend: 'neutral' },
            { label: 'Total Loans', value: '2,922', change: '', trend: 'neutral' },
        ],
        // Platforms 表格
        platforms: [
            { protocol: 'Figure', networks: ['Provenance'], totalLoans: 18335210707, activeLoans: 14569879467, avgBaseAPY: '—', defaultedLoans: '—' },
            { protocol: 'Tradable', networks: ['ZKSync Era'], totalLoans: 5259358966, activeLoans: 2302608838, avgBaseAPY: '11.24%', defaultedLoans: 0 },
            { protocol: 'Maple', networks: ['ETH', 'SOL'], totalLoans: 7115511518, activeLoans: 1625415133, avgBaseAPY: '9.16%', defaultedLoans: 47058378 },
            { protocol: 'PACT', networks: ['Aptos'], totalLoans: 1922062617, activeLoans: 599406297, avgBaseAPY: '22.32%', defaultedLoans: 156310107 },
            { protocol: 'Intain', networks: ['Intain'], totalLoans: 431881634, activeLoans: 431881634, avgBaseAPY: '5.72%', defaultedLoans: '—' },
            { protocol: 'MB | Mercado Bitcoin', networks: ['ETH', 'POL'], totalLoans: 354398677, activeLoans: 162909659, avgBaseAPY: '16.49%', defaultedLoans: 0 },
            { protocol: 'Centrifuge', networks: ['ETH', 'BASE', 'ARB'], totalLoans: 636296585, activeLoans: 73313204, avgBaseAPY: '8.71%', defaultedLoans: 0 },
            { protocol: 'Goldfinch', networks: ['—'], totalLoans: 171108808, activeLoans: 57173137, avgBaseAPY: '12.42%', defaultedLoans: 0 },
            { protocol: 'Credix', networks: ['—'], totalLoans: 46186993, activeLoans: 10828029, avgBaseAPY: '18.78%', defaultedLoans: 0 },
            { protocol: 'TrueFi', networks: ['Ethereum'], totalLoans: 1717045074, activeLoans: 7749704, avgBaseAPY: '—', defaultedLoans: 0 },
        ],
        // Pools 表格
        pools: [
            { platform: 'Maple', network: 'Ethereum', name: 'Syrup USDC', currency: 'USDC', status: 'OPEN', apy: '6.03%', principalOutstanding: 814998948, defaultedAmount: '—' },
            { platform: 'Maple', network: 'Ethereum', name: 'Syrup USDT', currency: 'USDT', status: 'OPEN', apy: '5.89%', principalOutstanding: 644327134, defaultedAmount: '—' },
            { platform: 'Intain', network: 'Intain', name: 'FIS-FLB1-CRE2025-1', currency: '—', status: '—', apy: '5.48%', principalOutstanding: 369935773, defaultedAmount: '—' },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: 'OPEN', apy: '11.31%', principalOutstanding: 189305238, defaultedAmount: 35377022 },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: 'OPEN', apy: '63.22%', principalOutstanding: 157863737, defaultedAmount: 114289102 },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: 'OPEN', apy: '0%', principalOutstanding: 104626099, defaultedAmount: '—' },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: '—', apy: '0%', principalOutstanding: 74309096, defaultedAmount: '—' },
            { platform: 'Maple', network: 'Ethereum', name: 'High Yield Secured Lending Maple Po...', currency: 'USDC', status: '—', apy: '5.18%', principalOutstanding: 73084447, defaultedAmount: '—' },
            { platform: 'Intain', network: 'Intain', name: 'FIS-FLB1-Aviation2025-1', currency: '—', status: '—', apy: '7.10%', principalOutstanding: 61945861, defaultedAmount: '—' },
            { platform: 'Goldfinch', network: 'Ethereum', name: 'Goldfinch Senior Pool', currency: 'USDC', status: 'OPEN', apy: '10.01%', principalOutstanding: 54838927, defaultedAmount: 3813060 },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: 'OPEN', apy: '0.13%', principalOutstanding: 44214265, defaultedAmount: '—' },
            { platform: 'Centrifuge', network: 'Ethereum', name: 'New Silver 2', currency: 'USDS', status: 'OPEN', apy: '8.45%', principalOutstanding: 33082496, defaultedAmount: '—' },
            { platform: 'Maple', network: 'Ethereum', name: 'Maven 11 wETH Pool', currency: 'wETH', status: 'OPEN', apy: '6.41%', principalOutstanding: 25978191, defaultedAmount: 12061303 },
            { platform: 'PACT', network: 'Aptos', name: 'Berkeley Square', currency: '—', status: 'OPEN', apy: '14.81%', principalOutstanding: 20578414, defaultedAmount: 3562693 },
            { platform: 'Credix', network: 'Solana', name: 'credix-marketplace', currency: 'USDC', status: 'OPEN', apy: '18.57%', principalOutstanding: 13688502, defaultedAmount: '—' },
        ],
        asOfDate: '01/14/2026',
    },

    // Institutional Funds 数据
    institutionalFundsData: {
        description: 'Explore the world of tokenized institutional alternatives, which encompasses hedge funds, venture capital, private equity, private credit, and other alternative investments.',
        metrics: [
            { label: 'Total Value', value: '$2.75B', change: '+1.03%', trend: 'up' },
            { label: 'Monthly Active Addresses', value: '4,265', change: '-14.39%', trend: 'down' },
            { label: 'Holders', value: '30,110', change: '+2.83%', trend: 'up' },
            { label: 'Total Funds', value: '35', change: '', trend: 'neutral' },
        ],
        // Total Value 按网络分布
        totalValueByNetwork: [
            { network: 'Ethereum', value: 1400000000, color: '#6B8AFF' },
            { network: 'Avalanche C-Chain', value: 614300000, color: '#E84142' },
            { network: 'ZKsync Era', value: 208500000, color: '#8C8DFC' },
            { network: 'Mantle', value: 172000000, color: '#000000' },
            { network: 'Solana', value: 138000000, color: '#9945FF' },
            { network: 'Plume', value: 74100000, color: '#FF6B6B' },
            { network: 'Polygon', value: 59700000, color: '#8247E5' },
        ],
        // League Table
        leagueTable: {
            platforms: [
                { rank: 1, name: 'Securitize', logo: '🔒', rwaCount: 15, totalValue: '$882.7M', change30d: '+16.98%', trend: 'up', marketShare: '32.08%' },
                { rank: 2, name: 'Centrifuge', logo: '🌀', rwaCount: 2, totalValue: '$873.9M', change30d: '-18.24%', trend: 'down', marketShare: '31.76%' },
                { rank: 3, name: 'Superstate', logo: '⚫', rwaCount: 1, totalValue: '$349.7M', change30d: '+29.69%', trend: 'up', marketShare: '12.71%' },
                { rank: 4, name: 'Tokeny', logo: '🟡', rwaCount: 2, totalValue: '$284.0M', change30d: '0%', trend: 'neutral', marketShare: '10.32%' },
                { rank: 5, name: 'Midas', logo: '💜', rwaCount: 1, totalValue: '$134.6M', change30d: '-9.67%', trend: 'down', marketShare: '4.89%' },
                { rank: 6, name: 'OnRe', logo: '⚪', rwaCount: 1, totalValue: '$83.9M', change30d: '+52.34%', trend: 'up', marketShare: '3.05%' },
                { rank: 7, name: 'Spiko', logo: '🔷', rwaCount: 2, totalValue: '$55.6M', change30d: '+3.37%', trend: 'up', marketShare: '2.02%' },
                { rank: 8, name: 'Republic', logo: '🔴', rwaCount: 1, totalValue: '$27.5M', change30d: '-2.13%', trend: 'down', marketShare: '1.00%' },
                { rank: 9, name: 'KAIO', logo: '🟢', rwaCount: 4, totalValue: '$24.4M', change30d: '+2.80%', trend: 'up', marketShare: '0.89%' },
                { rank: 10, name: 'Asseto', logo: '🟠', rwaCount: 1, totalValue: '$15.3M', change30d: '+0.44%', trend: 'up', marketShare: '0.56%' },
            ],
            managers: [
                { rank: 1, name: 'Janus Henderson', logo: '📊', rwaCount: 1, totalValue: '$822.9M', change30d: '-19.17%', trend: 'down', marketShare: '32.00%' },
                { rank: 2, name: 'Blockchain Capi...', logo: '🔵', rwaCount: 1, totalValue: '$356.9M', change30d: '-0.33%', trend: 'down', marketShare: '13.88%' },
                { rank: 3, name: 'Superstate', logo: '⚫', rwaCount: 1, totalValue: '$349.7M', change30d: '+29.69%', trend: 'up', marketShare: '13.60%' },
                { rank: 4, name: 'Skybridge Capital', logo: '📈', rwaCount: 2, totalValue: '$284.0M', change30d: '0%', trend: 'neutral', marketShare: '11.04%' },
                { rank: 5, name: 'Apollo Global M...', logo: '🟢', rwaCount: 2, totalValue: '$185.2M', change30d: '+1.52%', trend: 'up', marketShare: '7.20%' },
                { rank: 6, name: 'Fasanara', logo: '🔵', rwaCount: 1, totalValue: '$134.6M', change30d: '-9.67%', trend: 'down', marketShare: '5.23%' },
                { rank: 7, name: 'Insight North Am...', logo: '📊', rwaCount: 1, totalValue: '$106.3M', change30d: '+2,026%', trend: 'up', marketShare: '4.13%' },
                { rank: 8, name: 'On Re SAC Ltd', logo: '⚪', rwaCount: 1, totalValue: '$83.9M', change30d: '+52.34%', trend: 'up', marketShare: '3.26%' },
                { rank: 9, name: 'Twenty First Cap...', logo: '📈', rwaCount: 2, totalValue: '$55.6M', change30d: '+3.37%', trend: 'up', marketShare: '2.16%' },
                { rank: 10, name: 'Hamilton Lane', logo: '🔴', rwaCount: 4, totalValue: '$29.0M', change30d: '+90.61%', trend: 'up', marketShare: '1.13%' },
            ],
            networks: [
                { rank: 1, name: 'Ethereum', logo: '🔷', rwaCount: 19, totalValue: '$1.4B', change30d: '-2.54%', trend: 'down', marketShare: '51.13%' },
                { rank: 2, name: 'Avalanche C-Ch...', logo: '🔴', rwaCount: 14, totalValue: '$614.3M', change30d: '+1.72%', trend: 'up', marketShare: '22.33%' },
                { rank: 3, name: 'ZKsync Era', logo: '🔵', rwaCount: 1, totalValue: '$208.5M', change30d: '-0.56%', trend: 'down', marketShare: '7.58%' },
                { rank: 4, name: 'Mantle', logo: '⚫', rwaCount: 1, totalValue: '$172.0M', change30d: '+1.54%', trend: 'up', marketShare: '6.25%' },
                { rank: 5, name: 'Solana', logo: '🟣', rwaCount: 6, totalValue: '$138.0M', change30d: '+51.23%', trend: 'up', marketShare: '5.02%' },
                { rank: 6, name: 'Plume', logo: '🔴', rwaCount: 5, totalValue: '$74.1M', change30d: '-12.29%', trend: 'down', marketShare: '2.69%' },
                { rank: 7, name: 'Polygon', logo: '🟣', rwaCount: 8, totalValue: '$59.7M', change30d: '+25.04%', trend: 'up', marketShare: '2.17%' },
                { rank: 8, name: 'Aptos', logo: '🔷', rwaCount: 3, totalValue: '$32.3M', change30d: '+2.08%', trend: 'up', marketShare: '1.17%' },
                { rank: 9, name: 'SEI', logo: '🔴', rwaCount: 3, totalValue: '$19.2M', change30d: '+1.09%', trend: 'up', marketShare: '0.70%' },
                { rank: 10, name: 'Ink', logo: '🔵', rwaCount: 1, totalValue: '$10.9M', change30d: '+1.08%', trend: 'up', marketShare: '0.40%' },
            ],
            jurisdictions: [
                { rank: 1, name: 'United States of ...', logo: '🇺🇸', rwaCount: 20, totalValue: '$1.5B', change30d: '+8.55%', trend: 'up', marketShare: '55.62%' },
                { rank: 2, name: 'British Virgin Isla...', logo: '🇻🇬', rwaCount: 3, totalValue: '$980.2M', change30d: '-8.72%', trend: 'down', marketShare: '37.57%' },
                { rank: 3, name: 'Bermuda', logo: '🇧🇲', rwaCount: 1, totalValue: '$83.9M', change30d: '+52.34%', trend: 'up', marketShare: '3.22%' },
                { rank: 4, name: 'France', logo: '🇫🇷', rwaCount: 2, totalValue: '$55.6M', change30d: '+3.37%', trend: 'up', marketShare: '2.13%' },
                { rank: 5, name: 'Singapore', logo: '🇸🇬', rwaCount: 4, totalValue: '$22.9M', change30d: '+2.99%', trend: 'up', marketShare: '0.88%' },
                { rank: 6, name: 'Cayman Islands', logo: '🇰🇾', rwaCount: 1, totalValue: '$15.3M', change30d: '+0.44%', trend: 'up', marketShare: '0.59%' },
            ],
        },
        // Funds 产品列表
        funds: [
            { name: 'Janus Henderson Anemoy AAA CLO Fund', issuer: 'Anemoy', ticker: 'JAAA', platform: 'Centrifuge', networks: ['ETH', 'ARB'], marketCap: 822894661, nav: 1.02, holders: 10, sector: '—' },
            { name: 'Blockchain Capital III Digital Liquid Venture Fund', issuer: 'Blockchain Capital III Digital Liquid Venture Fund', ticker: 'BCAP', platform: 'Securitize', networks: ['ETH'], marketCap: 356852269, nav: 22.88, holders: 615, sector: '—' },
            { name: 'Superstate Crypto Carry Fund', issuer: 'Superstate Asset Trust', ticker: 'USCC', platform: 'Superstate', networks: ['ETH', 'SOL'], marketCap: 349651656, nav: 11.44, holders: 45, sector: 'Basis Trade' },
            { name: 'Legion Strategies, Ltd.', issuer: 'Legion Strategies', ticker: 'LS', platform: 'Tokeny', networks: ['AVAX'], marketCap: 217928797, nav: 1.00, holders: 1, sector: '—' },
            { name: 'Mantle Index Four Fund', issuer: 'Mantle Index Four', ticker: 'MI4', platform: 'Securitize', networks: ['Mantle'], marketCap: 172015232, nav: 127, holders: 8, sector: 'Crypto' },
            { name: 'Midas mF-ONE', issuer: 'Midas', ticker: 'mF-ONE', platform: 'Midas', networks: ['ETH'], marketCap: 134585532, nav: 1.05, holders: 27, sector: '—' },
            { name: 'Apollo Diversified Credit Securitize Fund', issuer: 'Securitize Tokenized Apollo Diversified Credit Fund', ticker: 'ACRED', platform: 'Securitize', networks: ['ETH'], marketCap: 134219268, nav: 1095, holders: 48, sector: '—' },
            { name: 'Securitize AAA CLO Tokenized Fund, Ltd', issuer: 'Securitize AAA CLO Tokenized Fund', ticker: 'STAC', platform: 'Securitize', networks: ['ETH'], marketCap: 106324272, nav: 1003, holders: 3, sector: 'Private Credit' },
            { name: 'OnRe Tokenized Reinsurance Fund', issuer: 'OnRe', ticker: '0Nyc', platform: 'OnRe', networks: ['SOL'], marketCap: 83881980, nav: 1.06, holders: 4333, sector: 'Crypto Reinsurance' },
            { name: 'Digital Macro Fund LTD', issuer: 'Digital Macro Fund', ticker: 'DMF', platform: 'Tokeny', networks: ['AVAX'], marketCap: 66043591, nav: 1.00, holders: 1, sector: 'Crypto' },
            { name: 'Anemoy Tokenized Apollo Diversified Credit Fund', issuer: 'Anemoy', ticker: 'ACRDX', platform: 'Centrifuge', networks: ['ETH'], marketCap: 50969607, nav: 1.02, holders: 1, sector: 'Private Credit' },
            { name: 'Spiko Cash & Carry Euro', issuer: 'Spiko', ticker: 'eurSPK...', platform: 'Spiko', networks: ['ETH', 'POL'], marketCap: 34099183, nav: 1.16, holders: 87, sector: 'Basis Trade' },
            { name: 'Republic NOTE', issuer: 'Republic', ticker: 'NOTE', platform: 'Republic', networks: ['AVAX'], marketCap: 27512830, nav: 0.09, holders: 7565, sector: 'Venture Capital' },
        ],
        asOfDate: '01/14/2026',
    },

    // Corporate Bonds 数据
    corporateBondsData: {
        description: 'View data on tokenized corporate bonds, digital assets that are backed by debt issued by companies. For data on tokenized U.S. Treasuries, click here. For data on tokenized non-U.S. government debt, click here.',
        metrics: [
            { label: 'Total Value', value: '$193.24M', change: '-0.03%', trend: 'down' },
            { label: 'Total Assets', value: '11', change: '', trend: 'neutral' },
            { label: 'Holders', value: '14,274', change: '-0.22%', trend: 'down' },
        ],
        // Top Entities
        topEntities: {
            platforms: [
                { rank: 1, name: 'Cashlink', logo: '💳', rwaCount: 3, totalValue: '$120.7M', change30d: '-0.58%', trend: 'down', marketShare: '62.48%' },
                { rank: 2, name: 'J.P. Morgan', logo: '🏦', rwaCount: 1, totalValue: '$50.0M', change30d: '0%', trend: 'neutral', marketShare: '25.87%' },
                { rank: 3, name: 'Backed Finance', logo: '🔵', rwaCount: 3, totalValue: '$13.2M', change30d: '+1.34%', trend: 'up', marketShare: '6.82%' },
                { rank: 4, name: 'Nest', logo: '🌿', rwaCount: 2, totalValue: '$5.1M', change30d: '+0.45%', trend: 'up', marketShare: '2.62%' },
                { rank: 5, name: 'Bitbond', logo: '🔷', rwaCount: 1, totalValue: '$3.1M', change30d: '-0.58%', trend: 'down', marketShare: '1.61%' },
                { rank: 6, name: 'WisdomTree', logo: '🌳', rwaCount: 1, totalValue: '$1.1M', change30d: '-0.63%', trend: 'down', marketShare: '0.59%' },
            ],
            managers: [
                { rank: 1, name: 'Nest', logo: '🌿', rwaCount: 2, totalValue: '$5.1M', change30d: '+0.45%', trend: 'up', marketShare: '81.58%' },
                { rank: 2, name: 'WisdomTree Digi...', logo: '🌳', rwaCount: 1, totalValue: '$1.1M', change30d: '-0.63%', trend: 'down', marketShare: '18.42%' },
            ],
            networks: [
                { rank: 1, name: 'Polygon', logo: '🟣', rwaCount: 3, totalValue: '$120.7M', change30d: '-0.58%', trend: 'down', marketShare: '62.48%' },
                { rank: 2, name: 'Solana', logo: '🟢', rwaCount: 1, totalValue: '$50.0M', change30d: '0%', trend: 'neutral', marketShare: '25.87%' },
                { rank: 3, name: 'Ethereum', logo: '🔷', rwaCount: 4, totalValue: '$13.2M', change30d: '+1.34%', trend: 'up', marketShare: '6.82%' },
                { rank: 4, name: 'Plume', logo: '🔴', rwaCount: 3, totalValue: '$5.1M', change30d: '+0.45%', trend: 'up', marketShare: '2.62%' },
                { rank: 5, name: 'Stellar', logo: '⚪', rwaCount: 2, totalValue: '$4.3M', change30d: '-0.59%', trend: 'down', marketShare: '2.20%' },
                { rank: 6, name: 'Arbitrum', logo: '🔵', rwaCount: 1, totalValue: '$1', change30d: '-0.77%', trend: 'down', marketShare: '0.00%' },
                { rank: 7, name: 'Base', logo: '🔵', rwaCount: 1, totalValue: '$0', change30d: '-0.77%', trend: 'down', marketShare: '0.00%' },
            ],
            jurisdictions: [
                { rank: 1, name: 'Germany', logo: '🇩🇪', rwaCount: 2, totalValue: '$116.7M', change30d: '-0.58%', trend: 'down', marketShare: '62.39%' },
                { rank: 2, name: 'United States of ...', logo: '🇺🇸', rwaCount: 1, totalValue: '$50.0M', change30d: '0%', trend: 'neutral', marketShare: '26.73%' },
                { rank: 3, name: 'Switzerland', logo: '🇨🇭', rwaCount: 3, totalValue: '$13.2M', change30d: '+1.34%', trend: 'up', marketShare: '7.05%' },
                { rank: 4, name: 'Luxembourg', logo: '🇱🇺', rwaCount: 2, totalValue: '$7.1M', change30d: '-0.58%', trend: 'down', marketShare: '3.82%' },
            ],
        },
        // Total Value 按资产分布
        totalValueByAsset: [
            { asset: 'NRW1', value: 116700000, color: '#6EE7B7' },
            { asset: 'Galaxy Tokenized U.S. Commercial Paper (US36317HAA23)', value: 50000000, color: '#6366F1' },
            { asset: 'Backed ERNX € Ultrashort Bond', value: 13000000, color: '#F97316' },
            { asset: 'Nest Institutional Vault', value: 5100000, color: '#FBBF24' },
            { asset: 'Lemonaid-Crowdinvesting', value: 4000000, color: '#A78BFA' },
        ],
        // Products 产品列表
        products: [
            { name: 'NRW1', issuer: 'NRW.BANK', ticker: 'NRW1', platform: 'Cashlink', networks: ['Polygon'], marketCap: 116695200, eligibleInvestors: 'Institutional Investor', holders: 1, issuerLegalName: 'NRW.BANK', domicile: 'Germany', license: 'German Electronic Securities Act' },
            { name: 'Galaxy Tokenized U.S. Commercial Paper (US36...', issuer: 'Galaxy Digital Holdings', ticker: 'US3631...', platform: 'J.P. Morgan', networks: ['Solana'], marketCap: 50000000, eligibleInvestors: '—', holders: 3, issuerLegalName: 'Galaxy Digital Holdings LP', domicile: 'United States of America', license: 'U.S. Securities Act Section 4(a)(2) exemption' },
            { name: 'Backed ERNX € Ultrashort Bond', issuer: 'Backed Assets', ticker: 'bERNX', platform: 'Backed Finance', networks: ['Ethereum'], marketCap: 12993600, eligibleInvestors: 'Non-U.S. Accredited / Professional Investor', holders: 2, issuerLegalName: 'Backed Assets (JE) Limited', domicile: 'Jersey, Channel Islands', license: 'Switzerland DLT Act' },
            { name: 'Nest Institutional Vault', issuer: 'Nest', ticker: 'nINST0', platform: 'Nest', networks: ['Plume'], marketCap: 5064345, eligibleInvestors: '—', holders: 10943, issuerLegalName: 'Nest DAO LLC', domicile: 'Republic of the Marshal...', license: '—' },
            { name: 'Lemonaid-Crowdinvesting', issuer: 'Lemonaid', ticker: 'LMA1', platform: 'Cashlink', networks: ['Polygon'], marketCap: 4032356, eligibleInvestors: 'Non-U.S. Investor', holders: 1472, issuerLegalName: 'Lemonaid Beverages GmbH', domicile: 'Germany', license: 'MiFID II' },
            { name: 'Bitbond BB1 tokenized bond', issuer: 'Bitbond', ticker: 'BB1', platform: 'Bitbond', networks: ['Stellar'], marketCap: 3113838, eligibleInvestors: '—', holders: 1178, issuerLegalName: 'Bitbond GmbH', domicile: 'Germany', license: 'MiFID II' },
            { name: 'WisdomTree Short-Duration Income Digital Fund', issuer: 'WisdomTree Short-Duration Income Digital Fund', ticker: 'WTSIX', platform: 'WisdomTree', networks: ['ETH', 'ARB', 'BASE'], marketCap: 1143589, eligibleInvestors: '—', holders: 53, issuerLegalName: 'WisdomTree Short-Duration Incom', domicile: 'United States of America', license: '—' },
            { name: 'Backed HIGH € High Yield Corp Bond', issuer: 'Backed Assets', ticker: 'bHIGH', platform: 'Backed Finance', networks: ['Ethereum'], marketCap: 194145, eligibleInvestors: '—', holders: 6, issuerLegalName: 'Backed Assets (JE) Limited', domicile: 'Jersey, Channel Islands', license: 'Switzerland DLT Act' },
            { name: 'Nest ETF Vault', issuer: 'Nest', ticker: 'nETF', platform: 'Nest', networks: ['Plume'], marketCap: 1881, eligibleInvestors: '—', holders: 615, issuerLegalName: 'Nest DAO LLC', domicile: 'Republic of the Marshal...', license: '—' },
            { name: 'KfW DLT I', issuer: 'KfW Bankengruppe', ticker: 'KFW', platform: 'Cashlink', networks: ['Polygon'], marketCap: 0, eligibleInvestors: 'Institutional Investor', holders: 1, issuerLegalName: 'Kreditanstalt für Wiederaufbau', domicile: 'Germany', license: 'German Electronic Securities Act' },
            { name: 'Backed ERNA $ Ultrashort Bond', issuer: 'Backed Assets', ticker: 'bERNA', platform: 'Backed Finance', networks: ['Ethereum'], marketCap: 0, eligibleInvestors: '—', holders: 0, issuerLegalName: 'Backed Assets (JE) Limited', domicile: 'Jersey, Channel Islands', license: 'Switzerland DLT Act' },
        ],
        asOfDate: '01/14/2026',
    },

    marketOverview: {
        title: 'Global Market Overview',
        subtitle: 'Welcome to RWA Insight. Explore tokenized real-world assets and the investors, issuers, and service providers participating on public blockchains.',
        metrics: [
            { label: 'Distributed Asset Value', value: '$20.81B', change: '+4.63%', trend: 'up' },
            { label: 'Represented Asset Value', value: '$282.68B', change: '-31.82%', trend: 'down' },
            { label: 'Total Asset Holders', value: '620,073', change: '+8.59%', trend: 'up' },
            { label: 'Total Stablecoin Value', value: '$297.68B', change: '-1.09%', trend: 'down' },
            { label: 'Total Stablecoin Holders', value: '220.12M', change: '+4.78%', trend: 'up' },
        ],
        categories: [
            { name: 'Private Credit', value: 45, color: '#10b981' },
            { name: 'Treasuries', value: 35, color: '#3b82f6' },
            { name: 'Real Estate', value: 20, color: '#f59e0b' },
        ],
        tvlTrend: [
            { date: '2025-12-01', tvl: 10.2 },
            { date: '2025-12-07', tvl: 10.8 },
            { date: '2025-12-14', tvl: 11.1 },
            { date: '2025-12-21', tvl: 11.5 },
            { date: '2025-12-28', tvl: 12.0 },
            { date: '2026-01-04', tvl: 12.3 },
            { date: '2026-01-11', tvl: 12.58 },
        ],
        macroIndicators: [
            { id: 'fed', name: 'Fed Funds Rate', value: '5.25 - 5.50%', status: 'Pause', trend: 'stable' },
            { id: 'cpi', name: 'CPI (YoY)', value: '3.1%', status: 'Decreasing', trend: 'down' },
            { id: 'vix', name: 'VIX Index', value: '13.45', status: 'Panic Free', trend: 'down' },
            { id: 'move', name: 'MOVE Index', value: '108.2', status: 'Elevated', trend: 'up' },
            { id: 'us10y', name: 'US 10Y Yield', value: '4.22%', status: 'Volatile', trend: 'up' },
        ],
        // Total RWA Value 分布
        totalRwaValue: [
            { name: 'US Treasury Debt', value: 9000000000, color: '#6B8AFF' },
            { name: 'Commodities', value: 3800000000, color: '#FBBF24' },
            { name: 'Private Credit', value: 3200000000, color: '#6366F1' },
            { name: 'Institutional Alternative Funds', value: 2500000000, color: '#94A3B8' },
            { name: 'Public Equity', value: 869600000, color: '#F97316' },
            { name: 'non-US Government Debt', value: 816900000, color: '#FB7185' },
            { name: 'Private Equity', value: 454100000, color: '#A78BFA' },
        ],
        // RWA League Table
        rwaLeagueTable: {
            networks: [
                { rank: 1, name: 'Canton', logo: '🟢', rwaCount: 7950, totalValue: '$345.3B', change30d: '-11.19%', trend: 'down', marketShare: '89.50%' },
                { rank: 2, name: 'Provenance', logo: '🔵', rwaCount: 1, totalValue: '$14.6B', change30d: '+2.70%', trend: 'up', marketShare: '3.78%' },
                { rank: 3, name: 'Ethereum', logo: '🔷', rwaCount: 643, totalValue: '$13.0B', change30d: '+1.83%', trend: 'up', marketShare: '3.37%' },
                { rank: 4, name: 'ZKsync Era', logo: '🔵', rwaCount: 48, totalValue: '$2.6B', change30d: '+10.93%', trend: 'up', marketShare: '0.66%' },
                { rank: 5, name: 'BNB Chain', logo: '🟡', rwaCount: 281, totalValue: '$2.1B', change30d: '+13.98%', trend: 'up', marketShare: '0.53%' },
                { rank: 6, name: 'Polygon', logo: '🟣', rwaCount: 281, totalValue: '$1.0B', change30d: '+3.23%', trend: 'up', marketShare: '0.27%' },
                { rank: 7, name: 'Liquid Network', logo: '🌐', rwaCount: 1, totalValue: '$1.0B', change30d: '+6.16%', trend: 'up', marketShare: '0.26%' },
                { rank: 8, name: 'Aptos', logo: '🔷', rwaCount: 14, totalValue: '$967.7M', change30d: '-0.64%', trend: 'down', marketShare: '0.25%' },
                { rank: 9, name: 'Solana', logo: '🟣', rwaCount: 305, totalValue: '$942.7M', change30d: '+10.73%', trend: 'up', marketShare: '0.24%' },
                { rank: 10, name: 'Stellar', logo: '⚪', rwaCount: 25, totalValue: '$894.9M', change30d: '+37.90%', trend: 'up', marketShare: '0.23%' },
            ],
            managers: [
                { rank: 1, name: 'Maple Protoc...', logo: '🟠', rwaCount: 2, totalValue: '$2.1B', change30d: '-12.70%', trend: 'down', marketShare: '10.81%' },
                { rank: 2, name: 'Tether', logo: '🟢', rwaCount: 1, totalValue: '$1.9B', change30d: '+15.38%', trend: 'up', marketShare: '10.02%' },
                { rank: 3, name: 'BlackRock', logo: '⚫', rwaCount: 7, totalValue: '$1.8B', change30d: '-5.02%', trend: 'down', marketShare: '9.35%' },
                { rank: 4, name: 'Paxos', logo: '🟢', rwaCount: 1, totalValue: '$1.8B', change30d: '+18.89%', trend: 'up', marketShare: '9.13%' },
                { rank: 5, name: 'Circle', logo: '🟢', rwaCount: 1, totalValue: '$1.5B', change30d: '+12.59%', trend: 'up', marketShare: '7.89%' },
                { rank: 6, name: 'Ondo', logo: '🔵', rwaCount: 2, totalValue: '$1.5B', change30d: '-1.24%', trend: 'down', marketShare: '7.83%' },
                { rank: 7, name: 'Janus Hender...', logo: '📊', rwaCount: 3, totalValue: '$1.2B', change30d: '-4.29%', trend: 'down', marketShare: '6.37%' },
                { rank: 8, name: 'SICOS Securi...', logo: '🔵', rwaCount: 1, totalValue: '$1.0B', change30d: '+6.16%', trend: 'up', marketShare: '5.29%' },
                { rank: 9, name: 'WisdomTree ...', logo: '🌳', rwaCount: 15, totalValue: '$780.5M', change30d: '+5.56%', trend: 'up', marketShare: '4.05%' },
                { rank: 10, name: 'China Asset ...', logo: '🔴', rwaCount: 12, totalValue: '$771.8M', change30d: '+0.35%', trend: 'up', marketShare: '4.01%' },
            ],
            platforms: [
                { rank: 1, name: 'Broadridge D...', logo: '🔷', rwaCount: 7950, totalValue: '$345.3B', change30d: '-11.19%', trend: 'down', marketShare: '89.50%' },
                { rank: 2, name: 'Figure', logo: '🔴', rwaCount: 1, totalValue: '$14.6B', change30d: '+2.70%', trend: 'up', marketShare: '3.78%' },
                { rank: 3, name: 'Securitize', logo: '🔒', rwaCount: 20, totalValue: '$3.2B', change30d: '+4.47%', trend: 'up', marketShare: '0.83%' },
                { rank: 4, name: 'Tradable', logo: '⚫', rwaCount: 46, totalValue: '$2.3B', change30d: '+12.34%', trend: 'up', marketShare: '0.60%' },
                { rank: 5, name: 'Maple', logo: '🟠', rwaCount: 4, totalValue: '$2.1B', change30d: '-12.70%', trend: 'down', marketShare: '0.54%' },
                { rank: 6, name: 'Ondo', logo: '🔵', rwaCount: 203, totalValue: '$2.0B', change30d: '+4.05%', trend: 'up', marketShare: '0.51%' },
                { rank: 7, name: 'Tether Holdings', logo: '🟢', rwaCount: 1, totalValue: '$1.9B', change30d: '+15.38%', trend: 'up', marketShare: '0.50%' },
                { rank: 8, name: 'Paxos', logo: '🟢', rwaCount: 1, totalValue: '$1.8B', change30d: '+18.89%', trend: 'up', marketShare: '0.46%' },
                { rank: 9, name: 'Circle', logo: '🟢', rwaCount: 1, totalValue: '$1.5B', change30d: '+12.59%', trend: 'up', marketShare: '0.39%' },
                { rank: 10, name: 'Centrifuge', logo: '🌀', rwaCount: 4, totalValue: '$1.3B', change30d: '-4.11%', trend: 'down', marketShare: '0.33%' },
            ],
            assetClasses: [
                { rank: 1, name: 'Repurchase Agre...', logo: '🌐', rwaCount: 7950, totalValue: '$345.3B', change30d: '-11.19%', trend: 'down', marketShare: '89.50%' },
                { rank: 2, name: 'Private Credit', logo: '💳', rwaCount: 756, totalValue: '$21.6B', change30d: '+2.21%', trend: 'up', marketShare: '5.60%' },
                { rank: 3, name: 'US Treasury Debt', logo: '🏛️', rwaCount: 59, totalValue: '$9.2B', change30d: '+2.66%', trend: 'up', marketShare: '2.40%' },
                { rank: 4, name: 'Commodities', logo: '💎', rwaCount: 21, totalValue: '$4.4B', change30d: '+18.60%', trend: 'up', marketShare: '1.14%' },
                { rank: 5, name: 'Institutional Altern...', logo: '🏢', rwaCount: 35, totalValue: '$2.8B', change30d: '+1.03%', trend: 'up', marketShare: '0.71%' },
                { rank: 6, name: 'Public Equity', logo: '📈', rwaCount: 389, totalValue: '$869.6M', change30d: '+23.96%', trend: 'up', marketShare: '0.23%' },
                { rank: 7, name: 'non-US Governm...', logo: '🌍', rwaCount: 19, totalValue: '$816.9M', change30d: '+24.35%', trend: 'up', marketShare: '0.21%' },
                { rank: 8, name: 'Private Equity', logo: '🔒', rwaCount: 6, totalValue: '$454.5M', change30d: '+22.30%', trend: 'up', marketShare: '0.12%' },
                { rank: 9, name: 'Corporate Bonds', logo: '🏦', rwaCount: 11, totalValue: '$193.2M', change30d: '-0.27%', trend: 'down', marketShare: '0.05%' },
                { rank: 10, name: 'Actively-Manage...', logo: '📊', rwaCount: 3, totalValue: '$172.5M', change30d: '+47.17%', trend: 'up', marketShare: '0.04%' },
            ],
        },
    },
    assets: [
        {
            id: 'tether-gold',
            name: 'Tether Gold',
            provider: 'Tether Holdings',
            symbol: 'XAUT',
            category: 'Commodities',
            apy: 0,
            tvl: 1893827300,
            investors: 21701,
            redemption: 'Daily',
            minInvestment: 200000,
            mgmtFee: 0,
            inception: '10/31/2021',
            jurisdiction: 'El Salvador',
            networks: ['Ethereum', 'Tron'],
            description: 'Tether Gold (XAUT) is a token that provides you ownership of physical gold allocated in a Swiss vault.',
            logo: 'https://gold.tether.to/favicon.ico',
            riskScore: 85,
            complianceTags: ['Swiss Audited', 'Physical Backed']
        },
        {
            id: 'buidl',
            name: 'BlackRock USD Institutional Digital Liquidity Fund',
            provider: 'Securitize',
            symbol: 'BUIDL',
            category: 'Institutional Funds',
            apy: 4.88,
            tvl: 1731829255,
            investors: 101,
            redemption: 'Daily',
            minInvestment: 5000000,
            mgmtFee: 0.50,
            inception: '03/20/2024',
            jurisdiction: 'British Virgin Islands',
            networks: ['Ethereum'],
            description: 'The investment objective of the BlackRock USD Institutional Digital Liquidity Fund is to provide current income as is consistent with liquidity.',
            logo: 'https://securitize.io/favicon.ico',
            riskScore: 98,
            complianceTags: ['SEC Registered', 'Institutional']
        },
        {
            id: 'makerdao',
            name: 'MakerDAO',
            provider: 'Maker Foundation',
            symbol: 'MKR',
            category: 'U.S. Treasuries',
            apy: 5.2,
            tvl: 2300000000,
            investors: 15400,
            redemption: 'Immediate',
            minInvestment: 0,
            mgmtFee: 0,
            inception: '12/17/2017',
            jurisdiction: 'DAO',
            networks: ['Ethereum'],
            description: 'MakerDAO enables users to issue and manage DAI, a decentralized stablecoin backed by overcollateralized assets including Treasuries.',
            logo: 'https://cryptologos.cc/logos/maker-mkr-logo.png',
            riskScore: 88,
            complianceTags: ['Institutional', 'DAO Managed']
        },
        {
            id: 'ondo',
            name: 'Ondo Finance',
            provider: 'Ondo I-LP',
            symbol: 'OUSG',
            category: 'U.S. Treasuries',
            apy: 4.8,
            tvl: 540000000,
            investors: 1250,
            redemption: 'Daily',
            minInvestment: 100000,
            mgmtFee: 0.15,
            inception: '01/15/2023',
            jurisdiction: 'United States',
            networks: ['Ethereum', 'Polygon'],
            description: 'OUSG provides tokenized access to a portfolio of short-term US Treasury bills held at institutional custodians.',
            logo: 'https://cryptologos.cc/logos/ondo-ondo-logo.png',
            riskScore: 94,
            complianceTags: ['SEC Regulated', 'US Based']
        },
        {
            id: 'matrixdock',
            name: 'Matrixdock',
            provider: 'Matrixport',
            symbol: 'STBT',
            category: 'U.S. Treasuries',
            apy: 5.15,
            tvl: 120000000,
            investors: 450,
            redemption: 'T+1',
            minInvestment: 1000,
            mgmtFee: 0.10,
            inception: '02/01/2023',
            jurisdiction: 'Seychelles',
            networks: ['Ethereum'],
            description: 'STBT offers transparent access to U.S. Treasury securities with daily proofs of reserve.',
            logo: 'https://www.matrixdock.com/favicon.ico',
            riskScore: 92,
            complianceTags: ['Institutional', 'Daily Proofs']
        }
    ],
    user: {
        address: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
        portfolio: {
            totalValue: 12500,
            assets: [
                { name: 'Ondo OUSG', value: 8500, change: 0.12 },
                { name: 'Maple Pool', value: 4000, change: 0.85 }
            ]
        }
    }
};
